---
extends:
- eslint:recommended
- plugin:prettier/recommended
- plugin:jest/recommended
plugins:
- import
root: true
env:
  es6: true
  node: true
  jest: true
rules:
  curly: error
  import/no-extraneous-dependencies:
  - error
  - devDependencies: ["tests*/**", "scripts/**"]
  no-else-return: error
  no-inner-declarations: error
  no-unneeded-ternary: error
  no-useless-return: error
  no-var: error
  one-var:
  - error
  - never
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: error
  prefer-template: error
  react/no-deprecated: off
  strict: error
  symbol-description: error
  yoda:
  - error
  - never
  - exceptRange: true
overrides:
- files: "tests/**/*.js"
  rules:
    strict: off
  globals:
    run_spec: true
